const express = require('express')
const router = express.Router()
const messageController = require('../controller/messageController')
const {isAuthenticated} = require('../middleware/authMiddleware')
router.get('/', isAuthenticated, messageController.getAllMessages)
router.get('/create', isAuthenticated, messageController.getMessageForm)
router.post('/create', isAuthenticated, messageController.createMessage)
router.get('/detail/:id', isAuthenticated, messageController.getMessageById)
router.post('/delete/:id', isAuthenticated, messageController.deleteMessage)
module.exports = router